
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  name: 'Default'

variables:
  solution: '**/*.sln'
  project:  '**/*Api.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(359b6ed0-9a63-4401-8bb6-19c83cf226ca)'
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tes  ts'
  inputs:
      command: 'test'
      projects: '**/*Tests.csproj'  
      arguments: '--configuration Release --no-build'
- task: DotNetCoreCLI@2
  displayName: 'Publish .NET Project'
  inputs:
    command: 'publish'
    projects: '$(project)'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/publish'
    zipAfterPublish: true

- task: AzureRmWebAppDeployment@5
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(359b6ed0-9a63-4401-8bb6-19c83cf226ca)'
    appType: 'webApp'
    WebAppName: 'TennisStatsApi'
    packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'

